logging:
  level:
    root: ERROR
    org:
      springframework: ERROR

  file:
    name: /Users/johnstoneananda/webshoplogs/temp/spring-boot-elk.log

server:
  port: 8090

spring:
  application:
    name: CustomerService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webshop-customers





