spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customerService
          uri: lb://CustomerService
          predicates:
            - Path=/customer/**
        - id: productService
          uri: lb://ProductService
          predicates:
            - Path=/product/**
        - id: shoppingCartService
          uri: lb://ShoppingCartService
          predicates:
            - Path=/cart/**
        - id: orderService
          uri: lb://OrderService
          predicates:
            - Path=/order/**
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

