logging:
  level:
    root: ERROR
    org:
      springframework: ERROR
  file:
    name: /Users/johnstoneananda/webshoplogs/temp/spring-boot-elk.log

server:
  port: 8501

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

spring:
  application:
    name: ShoppingCartService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webshop-shoppingcart-command

  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gid3
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: kafka
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)