logging:
  level:
    root: ERROR
    org:
      springframework: ERROR

server:
  port: 8902

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

spring:
  application:
    name: ProductService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: products

