logging:
  level:
    root: ERROR
    org:
      springframework: ERROR

server:
  port: 8502

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

spring:
  application:
    name: OrderService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orders
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

